version: '3.7'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run develop
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    networks:
      - webnet
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
    volumes:
      - mysqldata:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    networks:
      - webnet
    ports:
      - 3002:8080
    depends_on:
      - db


networks:
  webnet:

volumes:
  mysqldata: {}
